stages: # 定义了一条pipeline
  - 代码检测 # 定义了stage
  - 测试
  - 编译

  #- 发布JAR包

PMD扫描: # 定义了一个job
  stage: 代码检测 # 绑定到stage
  plugin: PMD # 指定使用的插件
  checkRule: # 校验结果
    - pmd1 = 0 && pmd2 = 0

STC扫描:
  stage: 代码检测
  plugin: STC
  checkRule:
    - stc = 0

单元测试:
  stage: 测试
  plugin: LINKQ-UT         # java单元测试插件
  checkRule:
    - passRate = 100
  tools:
    jdk: '1.8'  #jdk版本枚举：1.6、1.7、1.8
    maven: 3.2.5
  parameters:
    encoding: UTF-8 # 编码设置
    COVERAGE_EXCLUSIONS: '**/bootstrap/**,**/integration/**,**/client/pb/**,**/MetaApplication,**/registry/jraft/**,**/DataApplication,**/SessionApplication' # 覆盖率排除
  pluginConfig:
    markdown: admin/result.md # 向页面输出一些自定义内容
    aciTags: 8G

集成测试:
  stage: 测试
  plugin: LINKQ-IT         # java集成测试插件
  checkRule:
    - passRate = 100
  tools:
    jdk: '1.8'
  parameters:
    encoding: UTF-8 # 编码设置
  pluginConfig:
    privateRepo: false, # 是否是私有仓库
    parallelCount: 1 # 并发执行个数
    enableOracle: false # 是否依赖Oracle

编译:
  stage: 编译
  plugin: ANT-BUILD         # 使用插件ANT-BUILD
  pluginConfig:
    image: reg.docker.alibaba-inc.com/antb/sofa-build:0.0.2
    script:
      - export PATH=$PATH:/opt/taobao/java/bin:/opt/taobao/maven/bin
      - java -version
      - mvn -version
      - mvn clean package -Dmaven.test.skip=true -Palipay-dev
