ignore:
  - '**/bootstrap/**'
  - '**/inegration/**'
  - '**/client/pb/**'
  - '**/MetaApplication'
  - '**/registry/jraft/**'
  - '**/DataApplication'
  - '**/SessionApplication'
  - '**/RegistryApplication'

comment:
  behavior: default
  layout: reach,diff,flags,files,footer
  require_changes: false
