ignore:
  - '**/bootstrap/**'
  - '**/inegration/**'
  - '**/client/pb/**'
  - '**/MetaApplication'
  - '**/registry/jraft/**'
  - '**/DataApplication'
  - '**/SessionApplication'
  - '**/RegistryApplication'