/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AppRevisionRegisterPb.proto

package com.alipay.sofa.registry.common.model.client.pb;

/**
 * Protobuf type {@code AppRevisionInterfacePb}
 */
public final class AppRevisionInterfacePb extends com.google.protobuf.GeneratedMessageV3 implements
// @@protoc_insertion_point(message_implements:AppRevisionInterfacePb)
                                                                                        AppRevisionInterfacePbOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use AppRevisionInterfacePb.newBuilder() to construct.
    private AppRevisionInterfacePb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private AppRevisionInterfacePb() {
        dataId_ = "";
        group_ = "";
        instanceId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
        return this.unknownFields;
    }

    private AppRevisionInterfacePb(com.google.protobuf.CodedInputStream input,
                                   com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                               throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
            .newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        java.lang.String s = input.readStringRequireUtf8();

                        dataId_ = s;
                        break;
                    }
                    case 18: {
                        java.lang.String s = input.readStringRequireUtf8();

                        group_ = s;
                        break;
                    }
                    case 26: {
                        java.lang.String s = input.readStringRequireUtf8();

                        instanceId_ = s;
                        break;
                    }
                    case 34: {
                        if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                            serviceParams_ = com.google.protobuf.MapField
                                .newMapField(ServiceParamsDefaultEntryHolder.defaultEntry);
                            mutable_bitField0_ |= 0x00000008;
                        }
                        com.google.protobuf.MapEntry<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> serviceParams__ = input
                            .readMessage(
                                ServiceParamsDefaultEntryHolder.defaultEntry.getParserForType(),
                                extensionRegistry);
                        serviceParams_.getMutableMap().put(serviceParams__.getKey(),
                            serviceParams__.getValue());
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPbOuterClass.internal_static_AppRevisionInterfacePb_descriptor;
    }

    @SuppressWarnings({ "rawtypes" })
    protected com.google.protobuf.MapField internalGetMapField(int number) {
        switch (number) {
            case 4:
                return internalGetServiceParams();
            default:
                throw new RuntimeException("Invalid map field number: " + number);
        }
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPbOuterClass.internal_static_AppRevisionInterfacePb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb.class,
                com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb.Builder.class);
    }

    private int                       bitField0_;
    public static final int           DATAID_FIELD_NUMBER = 1;
    private volatile java.lang.Object dataId_;

    /**
     * <code>string dataId = 1;</code>
     */
    public java.lang.String getDataId() {
        java.lang.Object ref = dataId_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            dataId_ = s;
            return s;
        }
    }

    /**
     * <code>string dataId = 1;</code>
     */
    public com.google.protobuf.ByteString getDataIdBytes() {
        java.lang.Object ref = dataId_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                .copyFromUtf8((java.lang.String) ref);
            dataId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int           GROUP_FIELD_NUMBER = 2;
    private volatile java.lang.Object group_;

    /**
     * <code>string group = 2;</code>
     */
    public java.lang.String getGroup() {
        java.lang.Object ref = group_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            group_ = s;
            return s;
        }
    }

    /**
     * <code>string group = 2;</code>
     */
    public com.google.protobuf.ByteString getGroupBytes() {
        java.lang.Object ref = group_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                .copyFromUtf8((java.lang.String) ref);
            group_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int           INSTANCEID_FIELD_NUMBER = 3;
    private volatile java.lang.Object instanceId_;

    /**
     * <code>string instanceId = 3;</code>
     */
    public java.lang.String getInstanceId() {
        java.lang.Object ref = instanceId_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            instanceId_ = s;
            return s;
        }
    }

    /**
     * <code>string instanceId = 3;</code>
     */
    public com.google.protobuf.ByteString getInstanceIdBytes() {
        java.lang.Object ref = instanceId_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                .copyFromUtf8((java.lang.String) ref);
            instanceId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int SERVICEPARAMS_FIELD_NUMBER = 4;

    private static final class ServiceParamsDefaultEntryHolder {
        static final com.google.protobuf.MapEntry<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> defaultEntry = com.google.protobuf.MapEntry
                                                                                                                                                  .<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> newDefaultInstance(
                                                                                                                                                      com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPbOuterClass.internal_static_AppRevisionInterfacePb_ServiceParamsEntry_descriptor,
                                                                                                                                                      com.google.protobuf.WireFormat.FieldType.STRING,
                                                                                                                                                      "",
                                                                                                                                                      com.google.protobuf.WireFormat.FieldType.MESSAGE,
                                                                                                                                                      com.alipay.sofa.registry.common.model.client.pb.QueryValues
                                                                                                                                                          .getDefaultInstance());
    }

    private com.google.protobuf.MapField<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> serviceParams_;

    private com.google.protobuf.MapField<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> internalGetServiceParams() {
        if (serviceParams_ == null) {
            return com.google.protobuf.MapField
                .emptyMapField(ServiceParamsDefaultEntryHolder.defaultEntry);
        }
        return serviceParams_;
    }

    public int getServiceParamsCount() {
        return internalGetServiceParams().getMap().size();
    }

    /**
     * <code>map&lt;string, .QueryValues&gt; serviceParams = 4;</code>
     */

    public boolean containsServiceParams(java.lang.String key) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        return internalGetServiceParams().getMap().containsKey(key);
    }

    /**
     * Use {@link #getServiceParamsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> getServiceParams() {
        return getServiceParamsMap();
    }

    /**
     * <code>map&lt;string, .QueryValues&gt; serviceParams = 4;</code>
     */

    public java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> getServiceParamsMap() {
        return internalGetServiceParams().getMap();
    }

    /**
     * <code>map&lt;string, .QueryValues&gt; serviceParams = 4;</code>
     */

    public com.alipay.sofa.registry.common.model.client.pb.QueryValues getServiceParamsOrDefault(java.lang.String key,
                                                                                                 com.alipay.sofa.registry.common.model.client.pb.QueryValues defaultValue) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> map = internalGetServiceParams()
            .getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    /**
     * <code>map&lt;string, .QueryValues&gt; serviceParams = 4;</code>
     */

    public com.alipay.sofa.registry.common.model.client.pb.QueryValues getServiceParamsOrThrow(java.lang.String key) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> map = internalGetServiceParams()
            .getMap();
        if (!map.containsKey(key)) {
            throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (!getDataIdBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dataId_);
        }
        if (!getGroupBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, group_);
        }
        if (!getInstanceIdBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, instanceId_);
        }
        com.google.protobuf.GeneratedMessageV3.serializeStringMapTo(output,
            internalGetServiceParams(), ServiceParamsDefaultEntryHolder.defaultEntry, 4);
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;

        size = 0;
        if (!getDataIdBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dataId_);
        }
        if (!getGroupBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, group_);
        }
        if (!getInstanceIdBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, instanceId_);
        }
        for (java.util.Map.Entry<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> entry : internalGetServiceParams()
            .getMap().entrySet()) {
            com.google.protobuf.MapEntry<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> serviceParams__ = ServiceParamsDefaultEntryHolder.defaultEntry
                .newBuilderForType().setKey(entry.getKey()).setValue(entry.getValue()).build();
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(4, serviceParams__);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb)) {
            return super.equals(obj);
        }
        com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb other = (com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb) obj;

        boolean result = true;
        result = result && getDataId().equals(other.getDataId());
        result = result && getGroup().equals(other.getGroup());
        result = result && getInstanceId().equals(other.getInstanceId());
        result = result && internalGetServiceParams().equals(other.internalGetServiceParams());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + DATAID_FIELD_NUMBER;
        hash = (53 * hash) + getDataId().hashCode();
        hash = (37 * hash) + GROUP_FIELD_NUMBER;
        hash = (53 * hash) + getGroup().hashCode();
        hash = (37 * hash) + INSTANCEID_FIELD_NUMBER;
        hash = (53 * hash) + getInstanceId().hashCode();
        if (!internalGetServiceParams().getMap().isEmpty()) {
            hash = (37 * hash) + SERVICEPARAMS_FIELD_NUMBER;
            hash = (53 * hash) + internalGetServiceParams().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb parseFrom(java.nio.ByteBuffer data)
                                                                                                                            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb parseFrom(java.nio.ByteBuffer data,
                                                                                                   com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                               throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb parseFrom(com.google.protobuf.ByteString data)
                                                                                                                                       throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb parseFrom(com.google.protobuf.ByteString data,
                                                                                                   com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                               throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb parseFrom(byte[] data)
                                                                                                               throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb parseFrom(byte[] data,
                                                                                                   com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                               throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb parseFrom(java.io.InputStream input)
                                                                                                                             throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb parseFrom(java.io.InputStream input,
                                                                                                   com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                               throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
            extensionRegistry);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb parseDelimitedFrom(java.io.InputStream input)
                                                                                                                                      throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb parseDelimitedFrom(java.io.InputStream input,
                                                                                                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
            extensionRegistry);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb parseFrom(com.google.protobuf.CodedInputStream input)
                                                                                                                                              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb parseFrom(com.google.protobuf.CodedInputStream input,
                                                                                                   com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                               throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
            extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code AppRevisionInterfacePb}
     */
    public static final class Builder extends
                                     com.google.protobuf.GeneratedMessageV3.Builder<Builder>
                                                                                            implements
                                                                                            // @@protoc_insertion_point(builder_implements:AppRevisionInterfacePb)
                                                                                            com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePbOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPbOuterClass.internal_static_AppRevisionInterfacePb_descriptor;
        }

        @SuppressWarnings({ "rawtypes" })
        protected com.google.protobuf.MapField internalGetMapField(int number) {
            switch (number) {
                case 4:
                    return internalGetServiceParams();
                default:
                    throw new RuntimeException("Invalid map field number: " + number);
            }
        }

        @SuppressWarnings({ "rawtypes" })
        protected com.google.protobuf.MapField internalGetMutableMapField(int number) {
            switch (number) {
                case 4:
                    return internalGetMutableServiceParams();
                default:
                    throw new RuntimeException("Invalid map field number: " + number);
            }
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPbOuterClass.internal_static_AppRevisionInterfacePb_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb.class,
                    com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb.Builder.class);
        }

        // Construct using com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            dataId_ = "";

            group_ = "";

            instanceId_ = "";

            internalGetMutableServiceParams().clear();
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPbOuterClass.internal_static_AppRevisionInterfacePb_descriptor;
        }

        public com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb getDefaultInstanceForType() {
            return com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb
                .getDefaultInstance();
        }

        public com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb build() {
            com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb buildPartial() {
            com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb result = new com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb(
                this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            result.dataId_ = dataId_;
            result.group_ = group_;
            result.instanceId_ = instanceId_;
            result.serviceParams_ = internalGetServiceParams();
            result.serviceParams_.makeImmutable();
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field,
                                java.lang.Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
                                        int index, java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
                                        java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb) {
                return mergeFrom((com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb other) {
            if (other == com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb
                .getDefaultInstance())
                return this;
            if (!other.getDataId().isEmpty()) {
                dataId_ = other.dataId_;
                onChanged();
            }
            if (!other.getGroup().isEmpty()) {
                group_ = other.group_;
                onChanged();
            }
            if (!other.getInstanceId().isEmpty()) {
                instanceId_ = other.instanceId_;
                onChanged();
            }
            internalGetMutableServiceParams().mergeFrom(other.internalGetServiceParams());
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                                 com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                             throws java.io.IOException {
            com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb) e
                    .getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int              bitField0_;

        private java.lang.Object dataId_ = "";

        /**
         * <code>string dataId = 1;</code>
         */
        public java.lang.String getDataId() {
            java.lang.Object ref = dataId_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                dataId_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string dataId = 1;</code>
         */
        public com.google.protobuf.ByteString getDataIdBytes() {
            java.lang.Object ref = dataId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                    .copyFromUtf8((java.lang.String) ref);
                dataId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string dataId = 1;</code>
         */
        public Builder setDataId(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            dataId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string dataId = 1;</code>
         */
        public Builder clearDataId() {

            dataId_ = getDefaultInstance().getDataId();
            onChanged();
            return this;
        }

        /**
         * <code>string dataId = 1;</code>
         */
        public Builder setDataIdBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            dataId_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object group_ = "";

        /**
         * <code>string group = 2;</code>
         */
        public java.lang.String getGroup() {
            java.lang.Object ref = group_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                group_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string group = 2;</code>
         */
        public com.google.protobuf.ByteString getGroupBytes() {
            java.lang.Object ref = group_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                    .copyFromUtf8((java.lang.String) ref);
                group_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string group = 2;</code>
         */
        public Builder setGroup(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            group_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string group = 2;</code>
         */
        public Builder clearGroup() {

            group_ = getDefaultInstance().getGroup();
            onChanged();
            return this;
        }

        /**
         * <code>string group = 2;</code>
         */
        public Builder setGroupBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            group_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object instanceId_ = "";

        /**
         * <code>string instanceId = 3;</code>
         */
        public java.lang.String getInstanceId() {
            java.lang.Object ref = instanceId_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                instanceId_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string instanceId = 3;</code>
         */
        public com.google.protobuf.ByteString getInstanceIdBytes() {
            java.lang.Object ref = instanceId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                    .copyFromUtf8((java.lang.String) ref);
                instanceId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string instanceId = 3;</code>
         */
        public Builder setInstanceId(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            instanceId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string instanceId = 3;</code>
         */
        public Builder clearInstanceId() {

            instanceId_ = getDefaultInstance().getInstanceId();
            onChanged();
            return this;
        }

        /**
         * <code>string instanceId = 3;</code>
         */
        public Builder setInstanceIdBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            instanceId_ = value;
            onChanged();
            return this;
        }

        private com.google.protobuf.MapField<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> serviceParams_;

        private com.google.protobuf.MapField<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> internalGetServiceParams() {
            if (serviceParams_ == null) {
                return com.google.protobuf.MapField
                    .emptyMapField(ServiceParamsDefaultEntryHolder.defaultEntry);
            }
            return serviceParams_;
        }

        private com.google.protobuf.MapField<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> internalGetMutableServiceParams() {
            onChanged();
            ;
            if (serviceParams_ == null) {
                serviceParams_ = com.google.protobuf.MapField
                    .newMapField(ServiceParamsDefaultEntryHolder.defaultEntry);
            }
            if (!serviceParams_.isMutable()) {
                serviceParams_ = serviceParams_.copy();
            }
            return serviceParams_;
        }

        public int getServiceParamsCount() {
            return internalGetServiceParams().getMap().size();
        }

        /**
         * <code>map&lt;string, .QueryValues&gt; serviceParams = 4;</code>
         */

        public boolean containsServiceParams(java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            return internalGetServiceParams().getMap().containsKey(key);
        }

        /**
         * Use {@link #getServiceParamsMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> getServiceParams() {
            return getServiceParamsMap();
        }

        /**
         * <code>map&lt;string, .QueryValues&gt; serviceParams = 4;</code>
         */

        public java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> getServiceParamsMap() {
            return internalGetServiceParams().getMap();
        }

        /**
         * <code>map&lt;string, .QueryValues&gt; serviceParams = 4;</code>
         */

        public com.alipay.sofa.registry.common.model.client.pb.QueryValues getServiceParamsOrDefault(java.lang.String key,
                                                                                                     com.alipay.sofa.registry.common.model.client.pb.QueryValues defaultValue) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> map = internalGetServiceParams()
                .getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <code>map&lt;string, .QueryValues&gt; serviceParams = 4;</code>
         */

        public com.alipay.sofa.registry.common.model.client.pb.QueryValues getServiceParamsOrThrow(java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> map = internalGetServiceParams()
                .getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        public Builder clearServiceParams() {
            internalGetMutableServiceParams().getMutableMap().clear();
            return this;
        }

        /**
         * <code>map&lt;string, .QueryValues&gt; serviceParams = 4;</code>
         */

        public Builder removeServiceParams(java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            internalGetMutableServiceParams().getMutableMap().remove(key);
            return this;
        }

        /**
         * Use alternate mutation accessors instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> getMutableServiceParams() {
            return internalGetMutableServiceParams().getMutableMap();
        }

        /**
         * <code>map&lt;string, .QueryValues&gt; serviceParams = 4;</code>
         */
        public Builder putServiceParams(java.lang.String key,
                                        com.alipay.sofa.registry.common.model.client.pb.QueryValues value) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            if (value == null) {
                throw new java.lang.NullPointerException();
            }
            internalGetMutableServiceParams().getMutableMap().put(key, value);
            return this;
        }

        /**
         * <code>map&lt;string, .QueryValues&gt; serviceParams = 4;</code>
         */

        public Builder putAllServiceParams(java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> values) {
            internalGetMutableServiceParams().getMutableMap().putAll(values);
            return this;
        }

        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }

        // @@protoc_insertion_point(builder_scope:AppRevisionInterfacePb)
    }

    // @@protoc_insertion_point(class_scope:AppRevisionInterfacePb)
    private static final com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb DEFAULT_INSTANCE;
    static {
        DEFAULT_INSTANCE = new com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb();
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppRevisionInterfacePb> PARSER = new com.google.protobuf.AbstractParser<AppRevisionInterfacePb>() {
                                                                                       public AppRevisionInterfacePb parsePartialFrom(com.google.protobuf.CodedInputStream input,
                                                                                                                                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                                                  throws com.google.protobuf.InvalidProtocolBufferException {
                                                                                           return new AppRevisionInterfacePb(
                                                                                               input,
                                                                                               extensionRegistry);
                                                                                       }
                                                                                   };

    public static com.google.protobuf.Parser<AppRevisionInterfacePb> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppRevisionInterfacePb> getParserForType() {
        return PARSER;
    }

    public com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}
