/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AppRevisionRegisterPb.proto

package com.alipay.sofa.registry.common.model.client.pb;

public final class AppRevisionRegisterPbOuterClass {
    private AppRevisionRegisterPbOuterClass() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor                internal_static_AppRevisionRegisterPb_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_AppRevisionRegisterPb_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor                internal_static_AppRevisionRegisterPb_BaseParamsEntry_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_AppRevisionRegisterPb_BaseParamsEntry_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor                internal_static_AppRevisionInterfacePb_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_AppRevisionInterfacePb_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor                internal_static_AppRevisionInterfacePb_ServiceParamsEntry_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_AppRevisionInterfacePb_ServiceParamsEntry_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor                internal_static_QueryValues_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_QueryValues_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = { "\n\033AppRevisionRegisterPb.proto\"\344\001\n\025AppRev"
                                              + "isionRegisterPb\022\017\n\007appname\030\001 \001(\t\022\020\n\010revi"
                                              + "sion\030\002 \001(\t\022:\n\nbaseParams\030\004 \003(\0132&.AppRevi"
                                              + "sionRegisterPb.BaseParamsEntry\022+\n\ninterf"
                                              + "aces\030\005 \003(\0132\027.AppRevisionInterfacePb\032?\n\017B"
                                              + "aseParamsEntry\022\013\n\003key\030\001 \001(\t\022\033\n\005value\030\002 \001"
                                              + "(\0132\014.QueryValues:\0028\001\"\322\001\n\026AppRevisionInte"
                                              + "rfacePb\022\016\n\006dataId\030\001 \001(\t\022\r\n\005group\030\002 \001(\t\022\022"
                                              + "\n\ninstanceId\030\003 \001(\t\022A\n\rserviceParams\030\004 \003("
                                              + "\0132*.AppRevisionInterfacePb.ServiceParams"
                                              + "Entry\032B\n\022ServiceParamsEntry\022\013\n\003key\030\001 \001(\t"
                                              + "\022\033\n\005value\030\002 \001(\0132\014.QueryValues:\0028\001\"\035\n\013Que"
                                              + "ryValues\022\016\n\006values\030\001 \003(\tB:\n/com.alipay.s"
                                              + "ofa.registry.common.model.client.pbP\001Z\005p"
                                              + "rotob\006proto3" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
        internal_static_AppRevisionRegisterPb_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_AppRevisionRegisterPb_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_AppRevisionRegisterPb_descriptor, new java.lang.String[] { "Appname",
            "Revision", "BaseParams", "Interfaces", });
        internal_static_AppRevisionRegisterPb_BaseParamsEntry_descriptor = internal_static_AppRevisionRegisterPb_descriptor
            .getNestedTypes().get(0);
        internal_static_AppRevisionRegisterPb_BaseParamsEntry_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_AppRevisionRegisterPb_BaseParamsEntry_descriptor,
            new java.lang.String[] { "Key", "Value", });
        internal_static_AppRevisionInterfacePb_descriptor = getDescriptor().getMessageTypes()
            .get(1);
        internal_static_AppRevisionInterfacePb_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_AppRevisionInterfacePb_descriptor, new java.lang.String[] { "DataId",
            "Group", "InstanceId", "ServiceParams", });
        internal_static_AppRevisionInterfacePb_ServiceParamsEntry_descriptor = internal_static_AppRevisionInterfacePb_descriptor
            .getNestedTypes().get(0);
        internal_static_AppRevisionInterfacePb_ServiceParamsEntry_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_AppRevisionInterfacePb_ServiceParamsEntry_descriptor,
            new java.lang.String[] { "Key", "Value", });
        internal_static_QueryValues_descriptor = getDescriptor().getMessageTypes().get(2);
        internal_static_QueryValues_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_QueryValues_descriptor, new java.lang.String[] { "Values", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
