/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AppRevisionRegisterPb.proto

package com.alipay.sofa.registry.common.model.client.pb;

/**
 * Protobuf type {@code AppRevisionRegisterPb}
 */
public final class AppRevisionRegisterPb extends com.google.protobuf.GeneratedMessageV3 implements
// @@protoc_insertion_point(message_implements:AppRevisionRegisterPb)
                                                                                       AppRevisionRegisterPbOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use AppRevisionRegisterPb.newBuilder() to construct.
    private AppRevisionRegisterPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private AppRevisionRegisterPb() {
        appname_ = "";
        revision_ = "";
        interfaces_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
        return this.unknownFields;
    }

    private AppRevisionRegisterPb(com.google.protobuf.CodedInputStream input,
                                  com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                              throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
            .newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        java.lang.String s = input.readStringRequireUtf8();

                        appname_ = s;
                        break;
                    }
                    case 18: {
                        java.lang.String s = input.readStringRequireUtf8();

                        revision_ = s;
                        break;
                    }
                    case 34: {
                        if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                            baseParams_ = com.google.protobuf.MapField
                                .newMapField(BaseParamsDefaultEntryHolder.defaultEntry);
                            mutable_bitField0_ |= 0x00000004;
                        }
                        com.google.protobuf.MapEntry<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> baseParams__ = input
                            .readMessage(
                                BaseParamsDefaultEntryHolder.defaultEntry.getParserForType(),
                                extensionRegistry);
                        baseParams_.getMutableMap().put(baseParams__.getKey(),
                            baseParams__.getValue());
                        break;
                    }
                    case 42: {
                        if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                            interfaces_ = new java.util.ArrayList<com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb>();
                            mutable_bitField0_ |= 0x00000008;
                        }
                        interfaces_.add(input.readMessage(
                            com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb
                                .parser(), extensionRegistry));
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                interfaces_ = java.util.Collections.unmodifiableList(interfaces_);
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPbOuterClass.internal_static_AppRevisionRegisterPb_descriptor;
    }

    @SuppressWarnings({ "rawtypes" })
    protected com.google.protobuf.MapField internalGetMapField(int number) {
        switch (number) {
            case 4:
                return internalGetBaseParams();
            default:
                throw new RuntimeException("Invalid map field number: " + number);
        }
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPbOuterClass.internal_static_AppRevisionRegisterPb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb.class,
                com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb.Builder.class);
    }

    private int                       bitField0_;
    public static final int           APPNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object appname_;

    /**
     * <code>string appname = 1;</code>
     */
    public java.lang.String getAppname() {
        java.lang.Object ref = appname_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            appname_ = s;
            return s;
        }
    }

    /**
     * <code>string appname = 1;</code>
     */
    public com.google.protobuf.ByteString getAppnameBytes() {
        java.lang.Object ref = appname_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                .copyFromUtf8((java.lang.String) ref);
            appname_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int           REVISION_FIELD_NUMBER = 2;
    private volatile java.lang.Object revision_;

    /**
     * <code>string revision = 2;</code>
     */
    public java.lang.String getRevision() {
        java.lang.Object ref = revision_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            revision_ = s;
            return s;
        }
    }

    /**
     * <code>string revision = 2;</code>
     */
    public com.google.protobuf.ByteString getRevisionBytes() {
        java.lang.Object ref = revision_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                .copyFromUtf8((java.lang.String) ref);
            revision_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int BASEPARAMS_FIELD_NUMBER = 4;

    private static final class BaseParamsDefaultEntryHolder {
        static final com.google.protobuf.MapEntry<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> defaultEntry = com.google.protobuf.MapEntry
                                                                                                                                                  .<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> newDefaultInstance(
                                                                                                                                                      com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPbOuterClass.internal_static_AppRevisionRegisterPb_BaseParamsEntry_descriptor,
                                                                                                                                                      com.google.protobuf.WireFormat.FieldType.STRING,
                                                                                                                                                      "",
                                                                                                                                                      com.google.protobuf.WireFormat.FieldType.MESSAGE,
                                                                                                                                                      com.alipay.sofa.registry.common.model.client.pb.QueryValues
                                                                                                                                                          .getDefaultInstance());
    }

    private com.google.protobuf.MapField<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> baseParams_;

    private com.google.protobuf.MapField<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> internalGetBaseParams() {
        if (baseParams_ == null) {
            return com.google.protobuf.MapField
                .emptyMapField(BaseParamsDefaultEntryHolder.defaultEntry);
        }
        return baseParams_;
    }

    public int getBaseParamsCount() {
        return internalGetBaseParams().getMap().size();
    }

    /**
     * <code>map&lt;string, .QueryValues&gt; baseParams = 4;</code>
     */

    public boolean containsBaseParams(java.lang.String key) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        return internalGetBaseParams().getMap().containsKey(key);
    }

    /**
     * Use {@link #getBaseParamsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> getBaseParams() {
        return getBaseParamsMap();
    }

    /**
     * <code>map&lt;string, .QueryValues&gt; baseParams = 4;</code>
     */

    public java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> getBaseParamsMap() {
        return internalGetBaseParams().getMap();
    }

    /**
     * <code>map&lt;string, .QueryValues&gt; baseParams = 4;</code>
     */

    public com.alipay.sofa.registry.common.model.client.pb.QueryValues getBaseParamsOrDefault(java.lang.String key,
                                                                                              com.alipay.sofa.registry.common.model.client.pb.QueryValues defaultValue) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> map = internalGetBaseParams()
            .getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    /**
     * <code>map&lt;string, .QueryValues&gt; baseParams = 4;</code>
     */

    public com.alipay.sofa.registry.common.model.client.pb.QueryValues getBaseParamsOrThrow(java.lang.String key) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> map = internalGetBaseParams()
            .getMap();
        if (!map.containsKey(key)) {
            throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
    }

    public static final int                                                                        INTERFACES_FIELD_NUMBER = 5;
    private java.util.List<com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb> interfaces_;

    /**
     * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
     */
    public java.util.List<com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb> getInterfacesList() {
        return interfaces_;
    }

    /**
     * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
     */
    public java.util.List<? extends com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePbOrBuilder> getInterfacesOrBuilderList() {
        return interfaces_;
    }

    /**
     * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
     */
    public int getInterfacesCount() {
        return interfaces_.size();
    }

    /**
     * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
     */
    public com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb getInterfaces(int index) {
        return interfaces_.get(index);
    }

    /**
     * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
     */
    public com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePbOrBuilder getInterfacesOrBuilder(int index) {
        return interfaces_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (!getAppnameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appname_);
        }
        if (!getRevisionBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, revision_);
        }
        com.google.protobuf.GeneratedMessageV3.serializeStringMapTo(output,
            internalGetBaseParams(), BaseParamsDefaultEntryHolder.defaultEntry, 4);
        for (int i = 0; i < interfaces_.size(); i++) {
            output.writeMessage(5, interfaces_.get(i));
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;

        size = 0;
        if (!getAppnameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appname_);
        }
        if (!getRevisionBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, revision_);
        }
        for (java.util.Map.Entry<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> entry : internalGetBaseParams()
            .getMap().entrySet()) {
            com.google.protobuf.MapEntry<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> baseParams__ = BaseParamsDefaultEntryHolder.defaultEntry
                .newBuilderForType().setKey(entry.getKey()).setValue(entry.getValue()).build();
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(4, baseParams__);
        }
        for (int i = 0; i < interfaces_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(5, interfaces_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb)) {
            return super.equals(obj);
        }
        com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb other = (com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb) obj;

        boolean result = true;
        result = result && getAppname().equals(other.getAppname());
        result = result && getRevision().equals(other.getRevision());
        result = result && internalGetBaseParams().equals(other.internalGetBaseParams());
        result = result && getInterfacesList().equals(other.getInterfacesList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + APPNAME_FIELD_NUMBER;
        hash = (53 * hash) + getAppname().hashCode();
        hash = (37 * hash) + REVISION_FIELD_NUMBER;
        hash = (53 * hash) + getRevision().hashCode();
        if (!internalGetBaseParams().getMap().isEmpty()) {
            hash = (37 * hash) + BASEPARAMS_FIELD_NUMBER;
            hash = (53 * hash) + internalGetBaseParams().hashCode();
        }
        if (getInterfacesCount() > 0) {
            hash = (37 * hash) + INTERFACES_FIELD_NUMBER;
            hash = (53 * hash) + getInterfacesList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb parseFrom(java.nio.ByteBuffer data)
                                                                                                                           throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb parseFrom(java.nio.ByteBuffer data,
                                                                                                  com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb parseFrom(com.google.protobuf.ByteString data)
                                                                                                                                      throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb parseFrom(com.google.protobuf.ByteString data,
                                                                                                  com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb parseFrom(byte[] data)
                                                                                                              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb parseFrom(byte[] data,
                                                                                                  com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb parseFrom(java.io.InputStream input)
                                                                                                                            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb parseFrom(java.io.InputStream input,
                                                                                                  com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
            extensionRegistry);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb parseDelimitedFrom(java.io.InputStream input)
                                                                                                                                     throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb parseDelimitedFrom(java.io.InputStream input,
                                                                                                           com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                       throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
            extensionRegistry);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb parseFrom(com.google.protobuf.CodedInputStream input)
                                                                                                                                             throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb parseFrom(com.google.protobuf.CodedInputStream input,
                                                                                                  com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
            extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code AppRevisionRegisterPb}
     */
    public static final class Builder extends
                                     com.google.protobuf.GeneratedMessageV3.Builder<Builder>
                                                                                            implements
                                                                                            // @@protoc_insertion_point(builder_implements:AppRevisionRegisterPb)
                                                                                            com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPbOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPbOuterClass.internal_static_AppRevisionRegisterPb_descriptor;
        }

        @SuppressWarnings({ "rawtypes" })
        protected com.google.protobuf.MapField internalGetMapField(int number) {
            switch (number) {
                case 4:
                    return internalGetBaseParams();
                default:
                    throw new RuntimeException("Invalid map field number: " + number);
            }
        }

        @SuppressWarnings({ "rawtypes" })
        protected com.google.protobuf.MapField internalGetMutableMapField(int number) {
            switch (number) {
                case 4:
                    return internalGetMutableBaseParams();
                default:
                    throw new RuntimeException("Invalid map field number: " + number);
            }
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPbOuterClass.internal_static_AppRevisionRegisterPb_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb.class,
                    com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb.Builder.class);
        }

        // Construct using com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                getInterfacesFieldBuilder();
            }
        }

        public Builder clear() {
            super.clear();
            appname_ = "";

            revision_ = "";

            internalGetMutableBaseParams().clear();
            if (interfacesBuilder_ == null) {
                interfaces_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000008);
            } else {
                interfacesBuilder_.clear();
            }
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPbOuterClass.internal_static_AppRevisionRegisterPb_descriptor;
        }

        public com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb getDefaultInstanceForType() {
            return com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb
                .getDefaultInstance();
        }

        public com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb build() {
            com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb buildPartial() {
            com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb result = new com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb(
                this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            result.appname_ = appname_;
            result.revision_ = revision_;
            result.baseParams_ = internalGetBaseParams();
            result.baseParams_.makeImmutable();
            if (interfacesBuilder_ == null) {
                if (((bitField0_ & 0x00000008) == 0x00000008)) {
                    interfaces_ = java.util.Collections.unmodifiableList(interfaces_);
                    bitField0_ = (bitField0_ & ~0x00000008);
                }
                result.interfaces_ = interfaces_;
            } else {
                result.interfaces_ = interfacesBuilder_.build();
            }
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field,
                                java.lang.Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
                                        int index, java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
                                        java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb) {
                return mergeFrom((com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb other) {
            if (other == com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb
                .getDefaultInstance())
                return this;
            if (!other.getAppname().isEmpty()) {
                appname_ = other.appname_;
                onChanged();
            }
            if (!other.getRevision().isEmpty()) {
                revision_ = other.revision_;
                onChanged();
            }
            internalGetMutableBaseParams().mergeFrom(other.internalGetBaseParams());
            if (interfacesBuilder_ == null) {
                if (!other.interfaces_.isEmpty()) {
                    if (interfaces_.isEmpty()) {
                        interfaces_ = other.interfaces_;
                        bitField0_ = (bitField0_ & ~0x00000008);
                    } else {
                        ensureInterfacesIsMutable();
                        interfaces_.addAll(other.interfaces_);
                    }
                    onChanged();
                }
            } else {
                if (!other.interfaces_.isEmpty()) {
                    if (interfacesBuilder_.isEmpty()) {
                        interfacesBuilder_.dispose();
                        interfacesBuilder_ = null;
                        interfaces_ = other.interfaces_;
                        bitField0_ = (bitField0_ & ~0x00000008);
                        interfacesBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ? getInterfacesFieldBuilder()
                            : null;
                    } else {
                        interfacesBuilder_.addAllMessages(other.interfaces_);
                    }
                }
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                                 com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                             throws java.io.IOException {
            com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb) e
                    .getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int              bitField0_;

        private java.lang.Object appname_ = "";

        /**
         * <code>string appname = 1;</code>
         */
        public java.lang.String getAppname() {
            java.lang.Object ref = appname_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                appname_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string appname = 1;</code>
         */
        public com.google.protobuf.ByteString getAppnameBytes() {
            java.lang.Object ref = appname_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                    .copyFromUtf8((java.lang.String) ref);
                appname_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string appname = 1;</code>
         */
        public Builder setAppname(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            appname_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string appname = 1;</code>
         */
        public Builder clearAppname() {

            appname_ = getDefaultInstance().getAppname();
            onChanged();
            return this;
        }

        /**
         * <code>string appname = 1;</code>
         */
        public Builder setAppnameBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            appname_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object revision_ = "";

        /**
         * <code>string revision = 2;</code>
         */
        public java.lang.String getRevision() {
            java.lang.Object ref = revision_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                revision_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string revision = 2;</code>
         */
        public com.google.protobuf.ByteString getRevisionBytes() {
            java.lang.Object ref = revision_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                    .copyFromUtf8((java.lang.String) ref);
                revision_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string revision = 2;</code>
         */
        public Builder setRevision(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            revision_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string revision = 2;</code>
         */
        public Builder clearRevision() {

            revision_ = getDefaultInstance().getRevision();
            onChanged();
            return this;
        }

        /**
         * <code>string revision = 2;</code>
         */
        public Builder setRevisionBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            revision_ = value;
            onChanged();
            return this;
        }

        private com.google.protobuf.MapField<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> baseParams_;

        private com.google.protobuf.MapField<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> internalGetBaseParams() {
            if (baseParams_ == null) {
                return com.google.protobuf.MapField
                    .emptyMapField(BaseParamsDefaultEntryHolder.defaultEntry);
            }
            return baseParams_;
        }

        private com.google.protobuf.MapField<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> internalGetMutableBaseParams() {
            onChanged();
            ;
            if (baseParams_ == null) {
                baseParams_ = com.google.protobuf.MapField
                    .newMapField(BaseParamsDefaultEntryHolder.defaultEntry);
            }
            if (!baseParams_.isMutable()) {
                baseParams_ = baseParams_.copy();
            }
            return baseParams_;
        }

        public int getBaseParamsCount() {
            return internalGetBaseParams().getMap().size();
        }

        /**
         * <code>map&lt;string, .QueryValues&gt; baseParams = 4;</code>
         */

        public boolean containsBaseParams(java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            return internalGetBaseParams().getMap().containsKey(key);
        }

        /**
         * Use {@link #getBaseParamsMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> getBaseParams() {
            return getBaseParamsMap();
        }

        /**
         * <code>map&lt;string, .QueryValues&gt; baseParams = 4;</code>
         */

        public java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> getBaseParamsMap() {
            return internalGetBaseParams().getMap();
        }

        /**
         * <code>map&lt;string, .QueryValues&gt; baseParams = 4;</code>
         */

        public com.alipay.sofa.registry.common.model.client.pb.QueryValues getBaseParamsOrDefault(java.lang.String key,
                                                                                                  com.alipay.sofa.registry.common.model.client.pb.QueryValues defaultValue) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> map = internalGetBaseParams()
                .getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <code>map&lt;string, .QueryValues&gt; baseParams = 4;</code>
         */

        public com.alipay.sofa.registry.common.model.client.pb.QueryValues getBaseParamsOrThrow(java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> map = internalGetBaseParams()
                .getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        public Builder clearBaseParams() {
            internalGetMutableBaseParams().getMutableMap().clear();
            return this;
        }

        /**
         * <code>map&lt;string, .QueryValues&gt; baseParams = 4;</code>
         */

        public Builder removeBaseParams(java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            internalGetMutableBaseParams().getMutableMap().remove(key);
            return this;
        }

        /**
         * Use alternate mutation accessors instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> getMutableBaseParams() {
            return internalGetMutableBaseParams().getMutableMap();
        }

        /**
         * <code>map&lt;string, .QueryValues&gt; baseParams = 4;</code>
         */
        public Builder putBaseParams(java.lang.String key,
                                     com.alipay.sofa.registry.common.model.client.pb.QueryValues value) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            if (value == null) {
                throw new java.lang.NullPointerException();
            }
            internalGetMutableBaseParams().getMutableMap().put(key, value);
            return this;
        }

        /**
         * <code>map&lt;string, .QueryValues&gt; baseParams = 4;</code>
         */

        public Builder putAllBaseParams(java.util.Map<java.lang.String, com.alipay.sofa.registry.common.model.client.pb.QueryValues> values) {
            internalGetMutableBaseParams().getMutableMap().putAll(values);
            return this;
        }

        private java.util.List<com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb> interfaces_ = java.util.Collections
                                                                                                                       .emptyList();

        private void ensureInterfacesIsMutable() {
            if (!((bitField0_ & 0x00000008) == 0x00000008)) {
                interfaces_ = new java.util.ArrayList<com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb>(
                    interfaces_);
                bitField0_ |= 0x00000008;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb, com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb.Builder, com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePbOrBuilder> interfacesBuilder_;

        /**
         * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
         */
        public java.util.List<com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb> getInterfacesList() {
            if (interfacesBuilder_ == null) {
                return java.util.Collections.unmodifiableList(interfaces_);
            } else {
                return interfacesBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
         */
        public int getInterfacesCount() {
            if (interfacesBuilder_ == null) {
                return interfaces_.size();
            } else {
                return interfacesBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
         */
        public com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb getInterfaces(int index) {
            if (interfacesBuilder_ == null) {
                return interfaces_.get(index);
            } else {
                return interfacesBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
         */
        public Builder setInterfaces(int index,
                                     com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb value) {
            if (interfacesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureInterfacesIsMutable();
                interfaces_.set(index, value);
                onChanged();
            } else {
                interfacesBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
         */
        public Builder setInterfaces(int index,
                                     com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb.Builder builderForValue) {
            if (interfacesBuilder_ == null) {
                ensureInterfacesIsMutable();
                interfaces_.set(index, builderForValue.build());
                onChanged();
            } else {
                interfacesBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
         */
        public Builder addInterfaces(com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb value) {
            if (interfacesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureInterfacesIsMutable();
                interfaces_.add(value);
                onChanged();
            } else {
                interfacesBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
         */
        public Builder addInterfaces(int index,
                                     com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb value) {
            if (interfacesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureInterfacesIsMutable();
                interfaces_.add(index, value);
                onChanged();
            } else {
                interfacesBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
         */
        public Builder addInterfaces(com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb.Builder builderForValue) {
            if (interfacesBuilder_ == null) {
                ensureInterfacesIsMutable();
                interfaces_.add(builderForValue.build());
                onChanged();
            } else {
                interfacesBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
         */
        public Builder addInterfaces(int index,
                                     com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb.Builder builderForValue) {
            if (interfacesBuilder_ == null) {
                ensureInterfacesIsMutable();
                interfaces_.add(index, builderForValue.build());
                onChanged();
            } else {
                interfacesBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
         */
        public Builder addAllInterfaces(java.lang.Iterable<? extends com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb> values) {
            if (interfacesBuilder_ == null) {
                ensureInterfacesIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, interfaces_);
                onChanged();
            } else {
                interfacesBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
         */
        public Builder clearInterfaces() {
            if (interfacesBuilder_ == null) {
                interfaces_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000008);
                onChanged();
            } else {
                interfacesBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
         */
        public Builder removeInterfaces(int index) {
            if (interfacesBuilder_ == null) {
                ensureInterfacesIsMutable();
                interfaces_.remove(index);
                onChanged();
            } else {
                interfacesBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
         */
        public com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb.Builder getInterfacesBuilder(int index) {
            return getInterfacesFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
         */
        public com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePbOrBuilder getInterfacesOrBuilder(int index) {
            if (interfacesBuilder_ == null) {
                return interfaces_.get(index);
            } else {
                return interfacesBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
         */
        public java.util.List<? extends com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePbOrBuilder> getInterfacesOrBuilderList() {
            if (interfacesBuilder_ != null) {
                return interfacesBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(interfaces_);
            }
        }

        /**
         * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
         */
        public com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb.Builder addInterfacesBuilder() {
            return getInterfacesFieldBuilder().addBuilder(
                com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb
                    .getDefaultInstance());
        }

        /**
         * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
         */
        public com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb.Builder addInterfacesBuilder(int index) {
            return getInterfacesFieldBuilder().addBuilder(
                index,
                com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb
                    .getDefaultInstance());
        }

        /**
         * <code>repeated .AppRevisionInterfacePb interfaces = 5;</code>
         */
        public java.util.List<com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb.Builder> getInterfacesBuilderList() {
            return getInterfacesFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb, com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb.Builder, com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePbOrBuilder> getInterfacesFieldBuilder() {
            if (interfacesBuilder_ == null) {
                interfacesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb, com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePb.Builder, com.alipay.sofa.registry.common.model.client.pb.AppRevisionInterfacePbOrBuilder>(
                    interfaces_, ((bitField0_ & 0x00000008) == 0x00000008), getParentForChildren(),
                    isClean());
                interfaces_ = null;
            }
            return interfacesBuilder_;
        }

        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }

        // @@protoc_insertion_point(builder_scope:AppRevisionRegisterPb)
    }

    // @@protoc_insertion_point(class_scope:AppRevisionRegisterPb)
    private static final com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb DEFAULT_INSTANCE;
    static {
        DEFAULT_INSTANCE = new com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb();
    }

    public static com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppRevisionRegisterPb> PARSER = new com.google.protobuf.AbstractParser<AppRevisionRegisterPb>() {
                                                                                      public AppRevisionRegisterPb parsePartialFrom(com.google.protobuf.CodedInputStream input,
                                                                                                                                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                                                throws com.google.protobuf.InvalidProtocolBufferException {
                                                                                          return new AppRevisionRegisterPb(
                                                                                              input,
                                                                                              extensionRegistry);
                                                                                      }
                                                                                  };

    public static com.google.protobuf.Parser<AppRevisionRegisterPb> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppRevisionRegisterPb> getParserForType() {
        return PARSER;
    }

    public com.alipay.sofa.registry.common.model.client.pb.AppRevisionRegisterPb getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}
