version: '3.3'
services:
  sofa-registry:
    image: sofaregistry/sofaregistry:6.1.4
    container_name: sofa-registry-integration
    depends_on:
      - sofa-mysql
    links:
      - sofa-mysql
    restart: always
    ports:
      - 9615:9615
      - 9622:9622
      - 9603:9603
      - 9600:9600
    environment:
      JDBC_URL: jdbc:mysql://sofa-mysql:3306/registrymetadb?useSSL=false&useUnicode=true&characterEncoding=utf8
      JDBC_USERNAME: root
      JDBC_PASSWORD: root
      REGISTRY_APP_NAME: integration
    networks:
      - sofa-registry-ns
  sofa-mysql:
    image: mysql:5.7
    command: --init-file /docker-entrypoint-initdb.d/init.sql --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: sofa-registry-mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: registrymetadb
      TZ: Asia/Shanghai
    networks:
      - sofa-registry-ns
networks:
  sofa-registry-ns:
    driver: bridge